name: 错误反馈
description: 在使用 Cultivation-Way-Core 过程中遇到了错误
title: '[Bug]: '
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意填写错误反馈！
        ## 以下是一些注意事项，请务必阅读让我们能够更容易处理

        ### ❗ | 确定没有相同问题的ISSUE已被提出。
        ### 🌎| 请准确填写环境信息。
        ### ❔ | 提供出现问题前后至少 10 秒的完整日志内容。请自行删除日志内存在的个人信息及敏感内容。
        ### 如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》

        #### 在 Windows 下找到日志文件
        
        1. 在资源管理器路径栏中输入 C:/Users/user-name/AppData/LocalLow/mkarpenko/WorldBox 并按下 `Enter`。其中user-name为您的电脑用户名，需要自行替换。
        2. 找到名为 "Player.log" 的文件，右键点击并选择 "打开方式" -> "记事本"。
        3. 在记事本中按下 `Ctrl` + `A` 选中所有内容，然后按下 `Ctrl` + `C` 复制所有内容。
        4. 填入下方的 "日志记录" 栏中，注意删除其中的个人信息及敏感内容。
        
        #### 在 Arch Linux with Wayland 下找到日志文件
        
        1. `~/.config/unity3d/mkarpenko/WorldBox/Player.log`
        2. 填入下方的 "日志记录" 栏中，注意删除其中的个人信息及敏感内容。

        ### 在 MacOS 下找到日志文件

        1. 不知道怎么找，欢迎帮忙补充

        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经使用一个干净且无其它非必要的模组的环境测试过，问题依旧存在。"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/inmny/Cultivation-Way-Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。"
          required: true
        - label: 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
          required: true
        - label: 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
          required: true

  - type: markdown
    attributes:
      value: |
        ## 环境信息

  - type: input
    id: env-wb-ver
    attributes:
      label: WorldBox 版本
    validations:
      required: true

  - type: input
    id: env-CW-Core-ver
    attributes:
      label: Cultivation-Way-Core 版本 （或 Commit Id）
    validations:
      required: true

  - type: dropdown
    id: env-vm-ver
    attributes:
      label: 运行环境
      description: 选择系统版本
      options:
        - Windows (64)
        - Windows (32/x84)
        - MacOS
        - Ubuntu
        - CentOS
        - ArchLinux
        - 其它（请在下方说明）
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我们需要执行哪些操作才能让 Bug 出现？
        简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际的结果是什么？
    validations:
      required: true

  - type: textarea
    id: logging
    attributes:
      label: 日志记录

  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）